### ISSUE TITLE
.idea folder can be included into gitignore

### ISSUE THREAD

**Issue by slfmessi** [lcnju/CandyHeart#1]
RT, I think .idea folder can be included into gitignore file because there are only configure files about your IDE which dosent fit for everyone.
BTW, is lyc your gf? :)
<img src="http://hiphotos.baidu.com/y11r02/pic/item/8657a2c75eb3a8fd39db49bf.jpg" height="200px" width="200px"/>

**Comment by lcnju** [comment]
If I add .idea folder into gitignore, Android studio may not import this project.
Because there are some important file in .idea.
PS:yes

**Comment by slfmessi** [comment]
咱俩在这里说得这么严肃……觉得很有喜感……

**Comment by lcnju** [comment]
打英文简直......好难受.....

**Comment by lcnju** [comment]
果然.idea可以放弃了，而且所有*.iml都可以忽略
下面是我的.gitingore文件

    .gradle
    /local.properties
    .DS_Store
    /build
    /captures
    *.iml
    .idea

**Comment by slfmessi** [comment]
.DS_Store 所以说你买了MAC…？

**Comment by lcnju** [comment]
没有没有,这个是万一有用mac的人fork我（怎么可能有人fork）
